#!/bin/sh
set -e

# Inject runtime environment variables into JavaScript
# This allows configuring the frontend without rebuilding the image

cat > /usr/share/nginx/html/env-config.js << EOF
window.ENV = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-/api/v1}",
  VITE_ENV: "${VITE_ENV:-production}"
};
EOF

# Beta access gate configuration
# When BETA_PASSWORD is set, users must enter the code to access the site.
# The map matches the X-Beta-Token header against the configured password.
BETA_PASSWORD="${BETA_PASSWORD:-}"

if [ -n "$BETA_PASSWORD" ]; then
  cat > /etc/nginx/beta-gate.conf <<BETAEOF
# Beta gate ENABLED — password required
map \$http_x_beta_token \$beta_valid {
    default     "no";
    "$BETA_PASSWORD" "yes";
}
BETAEOF
  echo "Beta gate ENABLED"
else
  cat > /etc/nginx/beta-gate.conf <<BETAEOF
# Beta gate DISABLED — no BETA_PASSWORD set
map \$http_x_beta_token \$beta_valid {
    default "yes";
    ""      "yes";
}
BETAEOF
  echo "Beta gate disabled (no BETA_PASSWORD set)"
fi

# TLS / HTTPS configuration
# When TLS_DOMAIN is set and certs exist, enable HTTPS with HTTP redirect.
# Certs are expected at /etc/letsencrypt/live/$TLS_DOMAIN/ (mounted from host).
TLS_DOMAIN="${TLS_DOMAIN:-}"

if [ -n "$TLS_DOMAIN" ]; then
  CERT_PATH="/etc/letsencrypt/live/${TLS_DOMAIN}/fullchain.pem"
  KEY_PATH="/etc/letsencrypt/live/${TLS_DOMAIN}/privkey.pem"

  if [ -f "$CERT_PATH" ] && [ -f "$KEY_PATH" ]; then
    cat > /etc/nginx/conf.d/tls.conf <<TLSEOF
# TLS ENABLED for ${TLS_DOMAIN}
# Auto-generated by docker-entrypoint.sh

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name ${TLS_DOMAIN};

    # ACME challenge for cert renewal
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Health check still works over HTTP (for Docker healthcheck)
    location /health {
        access_log off;
        default_type text/plain;
        return 200 "healthy\n";
    }

    # Everything else redirects to HTTPS
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl;
    http2 on;
    server_name ${TLS_DOMAIN};

    ssl_certificate     ${CERT_PATH};
    ssl_certificate_key ${KEY_PATH};

    # Modern TLS config
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    root /usr/share/nginx/html;
    index index.html;

    # Service Worker
    location /service-worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Static assets with long cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)\$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Health check
    location /health {
        access_log off;
        default_type text/plain;
        return 200 "healthy\n";
    }

    # Beta verify
    location = /beta-verify {
        default_type text/plain;
        if (\$beta_valid = "yes") {
            return 200 'ok';
        }
        return 403 'forbidden';
    }

    # API proxy
    location /api/ {
        proxy_pass http://pilotlog-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # React Router
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    error_page 404 /index.html;
}
TLSEOF
    echo "TLS ENABLED for ${TLS_DOMAIN}"
  else
    echo "WARNING: TLS_DOMAIN=${TLS_DOMAIN} set but certs not found at ${CERT_PATH}"
    echo "Run certbot on the host first: certbot certonly --standalone -d ${TLS_DOMAIN}"
    echo "Falling back to HTTP only"
    # Write empty config
    echo "# TLS certs not found — HTTP only" > /etc/nginx/conf.d/tls.conf
  fi
else
  # No TLS — write empty config
  echo "# TLS disabled — no TLS_DOMAIN set" > /etc/nginx/conf.d/tls.conf
  echo "TLS disabled (no TLS_DOMAIN set)"
fi

# Execute the CMD
exec "$@"
