export { FEATURES, defineFeatures, getFeature } from './registry';
export type { Aircraft, FeatureDef, FeatureId, FeatureKind, RelevanceCtx } from './registry';
export { resolveRelevance } from './resolve';
export type { RelevanceCause, RelevanceDecision } from './resolve';
export { useRelevance, relevanceReason } from './useRelevance';
export type { Relevance } from './useRelevance';
export { toolkitLabel, toolkitName } from './names';
export { useRelevanceResolver } from './useRelevance';
export { classDiscipline, classPickerFeature, isDormantClass } from './classes';
export { ratingRank, sortRatingsByDiscipline } from './ratings';
