import type { components } from '../api/schema';

/**
 * Types for user-authored ("custom") currency rules.
 *
 * These are aliases onto the generated OpenAPI schema rather than hand-written
 * copies: the rule shapes are declared in ninerlog-api/api-spec/openapi.yaml
 * and regenerated by `npm run generate:api`, so a change on the API side shows
 * up here as a type error instead of silently disagreeing at runtime.
 */

type Schemas = components['schemas'];

export type CurrencyWindow = Schemas['CustomCurrencyWindow'];
export type CurrencyFilter = Schemas['CustomCurrencyFilter'];
export type CurrencyRequirementDef = Schemas['CustomCurrencyThreshold'];
export type CustomCurrencyRuleBody = Schemas['CustomCurrencyRuleBody'];
export type CustomCurrencyRule = Schemas['CustomCurrencyRule'];
export type CustomCurrencyEvaluation = Schemas['CustomCurrencyEvaluation'];
export type CustomRuleWithStatus = Schemas['CustomCurrencyRuleWithStatus'];
export type SharedRuleView = Schemas['SharedCustomCurrencyRule'];

/** Payload for create/update. */
export type CustomRuleInput = Schemas['CustomCurrencyRuleInput'];

export type WindowUnit = CurrencyWindow['unit'];
export type FilterOp = CurrencyFilter['op'];

/** The metrics a requirement may measure, as declared by the API. */
export type CurrencyMetric = CurrencyRequirementDef['metric'];

/** The fields a filter may reference, as declared by the API. */
export type CurrencyFilterField = CurrencyFilter['field'];

/**
 * The controlled vocabulary the builder offers. Typing `value` against the
 * generated enums means a metric the API drops or renames fails the build here
 * rather than reaching a user as a rejected rule.
 */
export const METRIC_OPTIONS: { value: CurrencyMetric; label: string; time: boolean }[] = [
  { value: 'flights', label: 'Flights', time: false },
  { value: 'landings', label: 'Landings', time: false },
  { value: 'day_landings', label: 'Day landings', time: false },
  { value: 'night_landings', label: 'Night landings', time: false },
  { value: 'takeoffs', label: 'Takeoffs', time: false },
  { value: 'day_takeoffs', label: 'Day takeoffs', time: false },
  { value: 'night_takeoffs', label: 'Night takeoffs', time: false },
  { value: 'approaches', label: 'Approaches', time: false },
  { value: 'holds', label: 'Holds', time: false },
  { value: 'total_time', label: 'Total time', time: true },
  { value: 'pic_time', label: 'PIC time', time: true },
  { value: 'dual_time', label: 'Dual time', time: true },
  { value: 'night_time', label: 'Night time', time: true },
  { value: 'ifr_time', label: 'Instrument time', time: true },
  { value: 'cross_country_time', label: 'Cross-country time', time: true },
];

/** Class types (mirrors models.ClassType) — used for eq/in value pickers. */
export const CLASS_TYPE_OPTIONS: { value: string; label: string }[] = [
  { value: 'SEP_LAND', label: 'SEP (Land)' },
  { value: 'SEP_SEA', label: 'SEP (Sea)' },
  { value: 'MEP_LAND', label: 'MEP (Land)' },
  { value: 'MEP_SEA', label: 'MEP (Sea)' },
  { value: 'SET_LAND', label: 'SET (Land)' },
  { value: 'SET_SEA', label: 'SET (Sea)' },
  { value: 'TMG', label: 'TMG' },
  { value: 'IR', label: 'Instrument Rating' },
  { value: 'OTHER', label: 'Other' },
];

/** Launch methods (mirrors flight.launch_method). */
export const LAUNCH_METHOD_OPTIONS: { value: string; label: string }[] = [
  { value: 'winch', label: 'Winch' },
  { value: 'aerotow', label: 'Aerotow' },
  { value: 'self-launch', label: 'Self-launch' },
];

export const FILTER_FIELD_OPTIONS: {
  value: CurrencyFilterField;
  label: string;
  ops: FilterOp[];
}[] = [
  { value: 'aircraft_class', label: 'Aircraft class', ops: ['eq', 'in'] },
  { value: 'aircraft_type', label: 'Aircraft type', ops: ['eq', 'in'] },
  { value: 'aircraft_registration', label: 'Registration', ops: ['eq', 'in'] },
  { value: 'launch_method', label: 'Launch method', ops: ['eq', 'in'] },
  { value: 'aircraft_complex', label: 'Complex aircraft', ops: ['is_true'] },
  { value: 'aircraft_high_performance', label: 'High-performance aircraft', ops: ['is_true'] },
  { value: 'aircraft_tailwheel', label: 'Tailwheel aircraft', ops: ['is_true'] },
  { value: 'is_pic', label: 'As PIC', ops: ['is_true'] },
  { value: 'is_dual', label: 'Dual', ops: ['is_true'] },
  { value: 'has_night', label: 'Has night time', ops: ['is_true'] },
  { value: 'has_ifr', label: 'Has instrument time', ops: ['is_true'] },
  { value: 'is_cross_country', label: 'Cross-country', ops: ['is_true'] },
];
