/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Create a new user account with email and password
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email and password to receive JWT tokens
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Use refresh token to obtain a new access token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Change the authenticated user's password. Requires the current password for verification.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start 2FA setup
         * @description Generate a TOTP secret and return the provisioning URI for authenticator apps. Does not enable 2FA until verified.
         */
        post: operations["setup2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify and enable 2FA
         * @description Verify a TOTP code to confirm setup and enable 2FA. Returns backup recovery codes.
         */
        post: operations["verify2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable 2FA
         * @description Disable two-factor authentication. Requires current password for confirmation.
         */
        post: operations["disable2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login with 2FA code
         * @description After initial login returns requiresTwoFactor, submit the TOTP code or recovery code here.
         */
        post: operations["login2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the authenticated user's profile information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /**
         * Delete current user account
         * @description Permanently delete the authenticated user's account and all associated data (licenses, flights, tokens). This action cannot be undone.
         */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Update the authenticated user's profile information
         */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/users/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get notification preferences
         * @description Get the authenticated user's notification preferences
         */
        get: operations["getNotificationPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update notification preferences
         * @description Update the authenticated user's notification preferences
         */
        patch: operations["updateNotificationPreferences"];
        trace?: never;
    };
    "/licenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's licenses
         * @description Get all licenses for the authenticated user
         */
        get: operations["listLicenses"];
        put?: never;
        /**
         * Create a new license
         * @description Add a new pilot license for the authenticated user
         */
        post: operations["createLicense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licenses/{licenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get license details
         * @description Retrieve details of a specific license
         */
        get: operations["getLicense"];
        put?: never;
        post?: never;
        /**
         * Delete license
         * @description Delete a license and all associated flight logs
         */
        delete: operations["deleteLicense"];
        options?: never;
        head?: never;
        /**
         * Update license
         * @description Update license information
         */
        patch: operations["updateLicense"];
        trace?: never;
    };
    "/licenses/{licenseId}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get license statistics
         * @description Get hour totals and flight counts for a license
         */
        get: operations["getLicenseStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licenses/{licenseId}/currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check currency status
         * @description Check if pilot is current according to EASA/FAA regulations
         */
        get: operations["getLicenseCurrency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List credentials
         * @description Get all credentials for the authenticated user
         */
        get: operations["listCredentials"];
        put?: never;
        /**
         * Add credential
         * @description Add a new credential (medical, language proficiency, or security clearance)
         */
        post: operations["createCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credentials/{credentialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get credential details */
        get: operations["getCredential"];
        put?: never;
        post?: never;
        /** Delete credential */
        delete: operations["deleteCredential"];
        options?: never;
        head?: never;
        /** Update credential */
        patch: operations["updateCredential"];
        trace?: never;
    };
    "/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List aircraft
         * @description Get all aircraft registered by the authenticated user
         */
        get: operations["listAircraft"];
        put?: never;
        /**
         * Add aircraft
         * @description Register a new aircraft to the user's database
         */
        post: operations["createAircraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aircraft/{aircraftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aircraft details
         * @description Get detailed information about a specific aircraft
         */
        get: operations["getAircraft"];
        put?: never;
        post?: never;
        /**
         * Delete aircraft
         * @description Delete an aircraft from the user's database. Note - flights using this aircraft will retain the registration/type as text.
         */
        delete: operations["deleteAircraft"];
        options?: never;
        head?: never;
        /**
         * Update aircraft
         * @description Update aircraft information
         */
        patch: operations["updateAircraft"];
        trace?: never;
    };
    "/flights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flights
         * @description Get flights for the authenticated user, optionally filtered by license
         */
        get: operations["listFlights"];
        put?: never;
        /**
         * Create flight log
         * @description Create a new flight log entry
         */
        post: operations["createFlight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flights/{flightId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flight details
         * @description Retrieve details of a specific flight
         */
        get: operations["getFlight"];
        /**
         * Update flight
         * @description Update an existing flight log entry
         */
        put: operations["updateFlight"];
        post?: never;
        /**
         * Delete flight
         * @description Delete a flight log entry
         */
        delete: operations["deleteFlight"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airports/{icaoCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get airport coordinates
         * @description Get coordinates and metadata for an airport by ICAO code
         */
        get: operations["getAirport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airports/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search airports
         * @description Search airports by ICAO code prefix
         */
        get: operations["searchAirports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flight routes for map
         * @description Get all unique flight routes with coordinates for map visualization
         */
        get: operations["getFlightRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/airport-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get airport statistics
         * @description Get flight count and hours per airport for the authenticated user
         */
        get: operations["getAirportStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @example pilot@example.com
             */
            email: string;
            /** @example John Doe */
            name: string;
            /**
             * Format: date-time
             * @example 2026-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T14:45:00Z
             */
            updatedAt: string;
            /**
             * @description Whether 2FA is enabled for this account
             * @example false
             */
            twoFactorEnabled?: boolean;
        };
        TwoFactorSetup: {
            /**
             * @description Base32-encoded TOTP secret for manual entry
             * @example JBSWY3DPEHPK3PXP
             */
            secret: string;
            /**
             * @description otpauth:// URI for QR code generation
             * @example otpauth://totp/PilotLog:pilot@example.com?secret=JBSWY3DPEHPK3PXP&issuer=PilotLog
             */
            qrUri: string;
        };
        TwoFactorEnabled: {
            /**
             * @description One-time recovery codes to use if authenticator is unavailable
             * @example [
             *       "abc12-def34",
             *       "ghi56-jkl78",
             *       "mno90-pqr12"
             *     ]
             */
            recoveryCodes: string[];
        };
        TwoFactorLoginRequired: {
            /** @example true */
            requiresTwoFactor: boolean;
            /** @description Temporary token to use with /auth/2fa/login */
            twoFactorToken: string;
        };
        AuthResponse: {
            /**
             * @description JWT access token (15 minutes validity)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description JWT refresh token (7 days validity)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
            /**
             * @description Access token expiry in seconds
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        /**
         * @description License type:
         *     - EASA_PPL: EASA Private Pilot License
         *     - FAA_PPL: FAA Private Pilot Certificate
         *     - EASA_SPL: EASA Sailplane Pilot License
         *     - FAA_SPORT: FAA Sport Pilot Certificate
         *     - EASA_CPL: EASA Commercial Pilot License
         *     - FAA_CPL: FAA Commercial Pilot Certificate
         *     - EASA_ATPL: EASA Airline Transport Pilot License
         *     - FAA_ATPL: FAA Airline Transport Pilot Certificate
         *     - EASA_IR: EASA Instrument Rating
         *     - FAA_IR: FAA Instrument Rating
         * @enum {string}
         */
        LicenseType: "EASA_PPL" | "FAA_PPL" | "EASA_SPL" | "FAA_SPORT" | "EASA_CPL" | "FAA_CPL" | "EASA_ATPL" | "FAA_ATPL" | "EASA_IR" | "FAA_IR";
        License: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            userId: string;
            licenseType: components["schemas"]["LicenseType"];
            /** @example PPL-123456 */
            licenseNumber: string;
            /**
             * Format: date
             * @example 2020-01-15
             */
            issueDate: string;
            /**
             * Format: date
             * @description Null if license doesn't expire
             * @example 2025-01-15
             */
            expiryDate?: string | null;
            /**
             * @description e.g., EASA, FAA, CAA UK
             * @example EASA
             */
            issuingAuthority: string;
            /**
             * @description Whether license is currently active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @example 2020-01-15T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T12:00:00Z
             */
            updatedAt: string;
        };
        LicenseCreate: {
            licenseType: components["schemas"]["LicenseType"];
            /** @example PPL-123456 */
            licenseNumber: string;
            /**
             * Format: date
             * @example 2020-01-15
             */
            issueDate: string;
            /**
             * Format: date
             * @example 2025-01-15
             */
            expiryDate?: string | null;
            /** @example EASA */
            issuingAuthority: string;
        };
        Aircraft: {
            /**
             * Format: uuid
             * @example 770e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId: string;
            /**
             * @description Aircraft registration/tail number
             * @example D-EFGH
             */
            registration: string;
            /**
             * @description Aircraft type designation (e.g., C172, PA28, ASK21)
             * @example C172
             */
            type: string;
            /**
             * @description Aircraft manufacturer
             * @example Cessna
             */
            make: string;
            /**
             * @description Aircraft model name
             * @example 172 Skyhawk
             */
            model: string;
            /**
             * @description Aircraft category (e.g., SEP - Single Engine Piston, MEP - Multi Engine Piston, TMG - Touring Motor Glider)
             * @example SEP
             */
            category?: string | null;
            /**
             * @description Engine type
             * @example piston
             * @enum {string|null}
             */
            engineType?: "piston" | "turboprop" | "jet" | "electric" | "null" | null;
            /**
             * @description Whether aircraft has retractable gear, flaps, and constant speed propeller
             * @default false
             * @example false
             */
            isComplex: boolean;
            /**
             * @description Whether aircraft has more than 200 HP
             * @default false
             * @example false
             */
            isHighPerformance: boolean;
            /**
             * @description Whether aircraft has tailwheel (conventional gear)
             * @default false
             * @example false
             */
            isTailwheel: boolean;
            /**
             * @description Additional notes about the aircraft
             * @example Club aircraft, requires checkout
             */
            notes?: string | null;
            /**
             * @description Whether aircraft is still active in the user's fleet
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @example 2026-01-15T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-02-01T14:30:00Z
             */
            updatedAt: string;
        };
        AircraftCreate: {
            /**
             * @description Aircraft registration/tail number
             * @example D-EFGH
             */
            registration: string;
            /**
             * @description Aircraft type designation
             * @example C172
             */
            type: string;
            /**
             * @description Aircraft manufacturer
             * @example Cessna
             */
            make: string;
            /**
             * @description Aircraft model name
             * @example 172 Skyhawk
             */
            model: string;
            /**
             * @description Aircraft category
             * @example SEP
             */
            category?: string | null;
            /**
             * @example piston
             * @enum {string|null}
             */
            engineType?: "piston" | "turboprop" | "jet" | "electric" | "null" | null;
            /**
             * @default false
             * @example false
             */
            isComplex: boolean;
            /**
             * @default false
             * @example false
             */
            isHighPerformance: boolean;
            /**
             * @default false
             * @example false
             */
            isTailwheel: boolean;
            /** @example Club aircraft, requires checkout */
            notes?: string | null;
        };
        AircraftUpdate: {
            /** @example D-EFGH */
            registration?: string;
            /** @example C172 */
            type?: string;
            /** @example Cessna */
            make?: string;
            /** @example 172 Skyhawk */
            model?: string;
            /** @example SEP */
            category?: string | null;
            /**
             * @example piston
             * @enum {string|null}
             */
            engineType?: "piston" | "turboprop" | "jet" | "electric" | "null" | null;
            /** @example false */
            isComplex?: boolean;
            /** @example false */
            isHighPerformance?: boolean;
            /** @example false */
            isTailwheel?: boolean;
            /** @example Club aircraft, requires checkout */
            notes?: string | null;
            /** @example true */
            isActive?: boolean;
        };
        Flight: {
            /**
             * Format: uuid
             * @example 770e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId: string;
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * Format: date
             * @example 2026-01-30
             */
            date: string;
            /**
             * @description Aircraft registration
             * @example D-EFGH
             */
            aircraftReg: string;
            /**
             * @description Aircraft type
             * @example C172
             */
            aircraftType: string;
            /**
             * @description ICAO code of departure airport
             * @example EDDF
             */
            departureIcao?: string | null;
            /**
             * @description ICAO code of arrival airport
             * @example EDDH
             */
            arrivalIcao?: string | null;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC. Marks the beginning of block time per EASA FCL.010 / FAA 14 CFR 1.1.
             * @example 14:15:00
             */
            offBlockTime?: string | null;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC. Marks the end of block time per EASA FCL.010 / FAA 14 CFR 1.1.
             * @example 16:55:00
             */
            onBlockTime?: string | null;
            /**
             * Format: time
             * @description Takeoff time in UTC. Marks the beginning of airborne/flight time.
             * @example 14:30:00
             */
            departureTime?: string | null;
            /**
             * Format: time
             * @description Landing time in UTC. Marks the end of airborne/flight time.
             * @example 16:45:00
             */
            arrivalTime?: string | null;
            /**
             * Format: float
             * @description Total block time in hours (off-block to on-block)
             * @example 2.5
             */
            totalTime: number;
            /**
             * @description Whether this flight was logged as pilot-in-command. Mutually exclusive with isDual.
             * @example true
             */
            isPic: boolean;
            /**
             * @description Whether this flight was logged as dual instruction received. Mutually exclusive with isPic.
             * @example false
             */
            isDual: boolean;
            /**
             * Format: float
             * @description Pilot-in-command block time in hours (computed from isPic and totalTime)
             * @example 2.5
             */
            picTime: number;
            /**
             * Format: float
             * @description Dual instruction block time in hours (computed from isDual and totalTime)
             * @example 0
             */
            dualTime: number;
            /**
             * Format: float
             * @description Night block time in hours
             * @example 0.5
             */
            nightTime: number;
            /**
             * Format: float
             * @description Instrument block time in hours
             * @example 1
             */
            ifrTime: number;
            /**
             * @description Number of day landings
             * @example 3
             */
            landingsDay: number;
            /**
             * @description Number of night landings
             * @example 1
             */
            landingsNight: number;
            /**
             * @description Free text notes
             * @example Training flight - touch and go practice
             */
            remarks?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-30T16:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-30T16:00:00Z
             */
            updatedAt: string;
        };
        FlightCreate: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * Format: date
             * @example 2026-01-30
             */
            date: string;
            /** @example D-EFGH */
            aircraftReg: string;
            /** @example C172 */
            aircraftType: string;
            /**
             * @description Departure airport ICAO code
             * @example EDDF
             */
            departureIcao: string;
            /**
             * @description Arrival airport ICAO code
             * @example EDDH
             */
            arrivalIcao: string;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC
             * @example 14:15:00
             */
            offBlockTime: string;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC
             * @example 16:55:00
             */
            onBlockTime: string;
            /**
             * Format: time
             * @description Takeoff time in UTC
             * @example 14:30:00
             */
            departureTime: string;
            /**
             * Format: time
             * @description Landing time in UTC
             * @example 16:45:00
             */
            arrivalTime: string;
            /**
             * Format: float
             * @description Total block time calculated from offBlockTime and onBlockTime. This field is computed by the server and should not be provided by the client.
             * @example 2.5
             */
            readonly totalTime?: number;
            /**
             * @description Whether this flight is logged as pilot-in-command. When true, picTime is set to totalTime. Mutually exclusive with isDual.
             * @default true
             * @example true
             */
            isPic: boolean;
            /**
             * @description Whether this flight is logged as dual instruction received. When true, dualTime is set to totalTime. Mutually exclusive with isPic.
             * @default false
             * @example false
             */
            isDual: boolean;
            /**
             * Format: float
             * @description Pilot-in-command time in hours. Computed by server — equals totalTime when isPic is true, 0 otherwise.
             * @example 2.5
             */
            readonly picTime?: number;
            /**
             * Format: float
             * @description Dual instruction time in hours. Computed by server — equals totalTime when isDual is true, 0 otherwise.
             * @example 0
             */
            readonly dualTime?: number;
            /**
             * Format: float
             * @default 0
             * @example 0.5
             */
            nightTime: number;
            /**
             * Format: float
             * @default 0
             * @example 1
             */
            ifrTime: number;
            /**
             * @description Number of day landings performed during this flight
             * @example 3
             */
            landingsDay: number;
            /**
             * @description Number of night landings performed during this flight
             * @example 1
             */
            landingsNight: number;
            /** @example Training flight - touch and go practice */
            remarks?: string | null;
        };
        FlightUpdate: {
            /** Format: date */
            date?: string;
            aircraftReg?: string;
            aircraftType?: string;
            departureIcao?: string | null;
            arrivalIcao?: string | null;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC
             */
            offBlockTime?: string | null;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC
             */
            onBlockTime?: string | null;
            /**
             * Format: time
             * @description Takeoff time in UTC
             */
            departureTime?: string | null;
            /**
             * Format: time
             * @description Landing time in UTC
             */
            arrivalTime?: string | null;
            /** Format: float */
            totalTime?: number;
            /** @description Whether this flight is logged as pilot-in-command */
            isPic?: boolean;
            /** @description Whether this flight is logged as dual instruction received */
            isDual?: boolean;
            /** Format: float */
            nightTime?: number;
            /** Format: float */
            ifrTime?: number;
            landingsDay?: number;
            landingsNight?: number;
            remarks?: string | null;
        };
        Statistics: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * @description Total number of flights
             * @example 150
             */
            totalFlights: number;
            /**
             * Format: float
             * @description Total block hours
             * @example 385.5
             */
            totalHours: number;
            /**
             * Format: float
             * @description Total PIC block hours
             * @example 320
             */
            picHours: number;
            /**
             * Format: float
             * @description Total dual instruction block hours
             * @example 45.5
             */
            dualHours: number;
            /**
             * Format: float
             * @description Total night block hours
             * @example 15.5
             */
            nightHours: number;
            /**
             * Format: float
             * @description Total IFR block hours
             * @example 30
             */
            ifrHours: number;
            /**
             * @description Total day landings
             * @example 450
             */
            landingsDay: number;
            /**
             * @description Total night landings
             * @example 35
             */
            landingsNight: number;
        };
        Currency: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * @description Overall currency status
             * @example true
             */
            isCurrent: boolean;
            /**
             * @description Day currency status
             * @example true
             */
            daysCurrent: boolean;
            /**
             * @description Night currency status (FAA requires separate tracking)
             * @example false
             */
            nightsCurrent: boolean;
            last90Days: {
                /**
                 * @description Number of flights in last 90 days
                 * @example 8
                 */
                flights: number;
                /**
                 * @description Total landings in last 90 days
                 * @example 15
                 */
                totalLandings: number;
                /**
                 * @description Day landings in last 90 days
                 * @example 12
                 */
                dayLandings: number;
                /**
                 * @description Night landings in last 90 days
                 * @example 3
                 */
                nightLandings: number;
            };
            requiredLandings?: {
                /**
                 * @description Required day landings for currency
                 * @example 3
                 */
                day: number;
                /**
                 * @description Required night landings for night currency
                 * @example 3
                 */
                night: number;
            };
            /**
             * Format: date
             * @description License expiry date if applicable
             * @example 2025-01-15
             */
            expiryDate?: string | null;
        };
        NotificationPreferences: {
            /**
             * @description Master switch for all email notifications
             * @example true
             */
            emailEnabled: boolean;
            /**
             * @description Email warnings when currency is about to expire
             * @example true
             */
            currencyWarnings: boolean;
            /**
             * @description Email warnings when credentials (medicals, etc.) are about to expire
             * @example true
             */
            credentialWarnings: boolean;
            /**
             * @description Days before expiry to send warnings
             * @example [
             *       30,
             *       14,
             *       7
             *     ]
             */
            warningDays: number[];
        };
        NotificationPreferencesUpdate: {
            emailEnabled?: boolean;
            currencyWarnings?: boolean;
            credentialWarnings?: boolean;
            warningDays?: number[];
        };
        /**
         * @description Credential type:
         *     - EASA_CLASS1_MEDICAL: EASA Class 1 Medical Certificate
         *     - EASA_CLASS2_MEDICAL: EASA Class 2 Medical Certificate
         *     - EASA_LAPL_MEDICAL: EASA LAPL Medical Certificate
         *     - FAA_CLASS1_MEDICAL: FAA First-Class Medical Certificate
         *     - FAA_CLASS2_MEDICAL: FAA Second-Class Medical Certificate
         *     - FAA_CLASS3_MEDICAL: FAA Third-Class Medical Certificate
         *     - LANG_ICAO_LEVEL4: Language Proficiency ICAO Level 4
         *     - LANG_ICAO_LEVEL5: Language Proficiency ICAO Level 5
         *     - LANG_ICAO_LEVEL6: Language Proficiency ICAO Level 6 (Expert)
         *     - SEC_CLEARANCE_ZUP: Security Clearance ZÜP (Germany)
         *     - SEC_CLEARANCE_ZUBB: Security Clearance ZüBB (Germany)
         *     - OTHER: Other credential
         * @enum {string}
         */
        CredentialType: "EASA_CLASS1_MEDICAL" | "EASA_CLASS2_MEDICAL" | "EASA_LAPL_MEDICAL" | "FAA_CLASS1_MEDICAL" | "FAA_CLASS2_MEDICAL" | "FAA_CLASS3_MEDICAL" | "LANG_ICAO_LEVEL4" | "LANG_ICAO_LEVEL5" | "LANG_ICAO_LEVEL6" | "SEC_CLEARANCE_ZUP" | "SEC_CLEARANCE_ZUBB" | "OTHER";
        Credential: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            credentialType: components["schemas"]["CredentialType"];
            /**
             * @description Official credential number/reference
             * @example MED-2026-001
             */
            credentialNumber?: string | null;
            /**
             * Format: date
             * @example 2026-01-15
             */
            issueDate: string;
            /**
             * Format: date
             * @description Null if credential doesn't expire
             * @example 2027-01-15
             */
            expiryDate?: string | null;
            /**
             * @description Authority or examiner that issued the credential
             * @example EASA AME
             */
            issuingAuthority: string;
            /** @example Annual renewal required */
            notes?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CredentialCreate: {
            credentialType: components["schemas"]["CredentialType"];
            credentialNumber?: string | null;
            /** Format: date */
            issueDate: string;
            /** Format: date */
            expiryDate?: string | null;
            issuingAuthority: string;
            notes?: string | null;
        };
        CredentialUpdate: {
            credentialType?: components["schemas"]["CredentialType"];
            credentialNumber?: string | null;
            /** Format: date */
            issueDate?: string;
            /** Format: date */
            expiryDate?: string | null;
            issuingAuthority?: string;
            notes?: string | null;
        };
        PaginatedFlights: {
            data: components["schemas"]["Flight"][];
            pagination: {
                /**
                 * @description Current page (1-indexed)
                 * @example 1
                 */
                page: number;
                /**
                 * @description Items per page
                 * @example 20
                 */
                pageSize: number;
                /**
                 * @description Total number of items
                 * @example 150
                 */
                total: number;
                /**
                 * @description Total number of pages
                 * @example 8
                 */
                totalPages: number;
            };
        };
        PaginatedAircraft: {
            data: components["schemas"]["Aircraft"][];
            pagination: {
                /**
                 * @description Current page (1-indexed)
                 * @example 1
                 */
                page: number;
                /**
                 * @description Items per page
                 * @example 20
                 */
                pageSize: number;
                /**
                 * @description Total number of items
                 * @example 25
                 */
                total: number;
                /**
                 * @description Total number of pages
                 * @example 2
                 */
                totalPages: number;
            };
        };
        Airport: {
            /**
             * @description ICAO airport code
             * @example EDDF
             */
            icao: string;
            /**
             * @description Airport name
             * @example Frankfurt am Main
             */
            name: string;
            /**
             * Format: double
             * @description Latitude in decimal degrees
             * @example 50.033333
             */
            latitude: number;
            /**
             * Format: double
             * @description Longitude in decimal degrees
             * @example 8.570556
             */
            longitude: number;
            /**
             * @description Airport elevation in feet
             * @example 364
             */
            elevation?: number;
            /**
             * @description Country code (ISO 3166-1 alpha-2)
             * @example DE
             */
            country?: string;
        };
        FlightRoute: {
            /** @example EDDF */
            departureIcao: string;
            /** @example EDDH */
            arrivalIcao: string;
            departureCoords: {
                /** Format: double */
                lat: number;
                /** Format: double */
                lng: number;
            };
            arrivalCoords: {
                /** Format: double */
                lat: number;
                /** Format: double */
                lng: number;
            };
            /**
             * @description Number of flights on this route
             * @example 5
             */
            flightCount: number;
        };
        FlightRoutesResponse: {
            routes: components["schemas"]["FlightRoute"][];
            airports: components["schemas"]["Airport"][];
        };
        AirportStats: {
            /** @example EDDF */
            icao: string;
            /** @example Frankfurt am Main */
            name: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** @description Number of departures from this airport */
            departures: number;
            /** @description Number of arrivals to this airport */
            arrivals: number;
            /** @description Total flights (departures + arrivals) */
            totalFlights: number;
        };
        Error: {
            /**
             * @description Error message
             * @example Validation failed
             */
            error: string;
            /** @description Detailed validation errors */
            details?: {
                /** @example totalTime */
                field?: string;
                /** @example Must be greater than 0 */
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Bad request - validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Validation failed",
                 *       "details": [
                 *         {
                 *           "field": "totalTime",
                 *           "message": "Must be greater than 0"
                 *         },
                 *         {
                 *           "field": "nightTime",
                 *           "message": "Cannot exceed total time"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description License UUID */
        LicenseId: string;
        /** @description Aircraft UUID */
        AircraftId: string;
        /** @description Flight UUID */
        FlightId: string;
        /** @description Credential UUID */
        CredentialId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example pilot@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @description Must be at least 8 characters
                     * @example SecurePass123!
                     */
                    password: string;
                    /** @example John Doe */
                    name: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example pilot@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example SecurePass123!
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Token expiry in seconds */
                        expiresIn?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: password
                     * @description The user's current password
                     */
                    currentPassword: string;
                    /**
                     * Format: password
                     * @description The new password (minimum 8 characters)
                     */
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    setup2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2FA setup data with secret and QR URI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorSetup"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 2FA is already enabled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verify2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 6-digit TOTP code from authenticator app */
                    code: string;
                };
            };
        };
        responses: {
            /** @description 2FA enabled with recovery codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorEnabled"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    disable2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 2FA disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    login2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Temporary token from login response */
                    twoFactorToken: string;
                    /** @description 6-digit TOTP code or recovery code */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: password
                     * @description Current password for confirmation
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Account deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Preferences updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listLicenses: {
        parameters: {
            query?: {
                /** @description Filter by active status */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of licenses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLicense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LicenseCreate"];
            };
        };
        responses: {
            /** @description License created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    expiryDate?: string | null;
                    isActive?: boolean;
                };
            };
        };
        responses: {
            /** @description License updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLicenseStatistics: {
        parameters: {
            query?: {
                /** @description Filter from this date (inclusive) */
                startDate?: string;
                /** @description Filter to this date (inclusive) */
                endDate?: string;
            };
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statistics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLicenseCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currency status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialCreate"];
            };
        };
        responses: {
            /** @description Credential created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential UUID */
                credentialId: components["parameters"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential UUID */
                credentialId: components["parameters"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential UUID */
                credentialId: components["parameters"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialUpdate"];
            };
        };
        responses: {
            /** @description Credential updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAircraft: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of aircraft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAircraft"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AircraftCreate"];
            };
        };
        responses: {
            /** @description Aircraft created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Aircraft registration already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Aircraft UUID */
                aircraftId: components["parameters"]["AircraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aircraft details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Aircraft UUID */
                aircraftId: components["parameters"]["AircraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aircraft deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Aircraft UUID */
                aircraftId: components["parameters"]["AircraftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AircraftUpdate"];
            };
        };
        responses: {
            /** @description Aircraft updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listFlights: {
        parameters: {
            query?: {
                /** @description Filter by license ID */
                licenseId?: string;
                /** @description Filter from this date (inclusive) */
                startDate?: string;
                /** @description Filter to this date (inclusive) */
                endDate?: string;
                /** @description Filter by aircraft registration */
                aircraftReg?: string;
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
                /** @description Sort field */
                sortBy?: "date" | "totalTime" | "createdAt";
                /** @description Sort order */
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of flights */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFlights"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFlight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightCreate"];
            };
        };
        responses: {
            /** @description Flight created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightUpdate"];
            };
        };
        responses: {
            /** @description Flight updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAirport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ICAO airport code (4 characters) */
                icaoCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchAirports: {
        parameters: {
            query: {
                /** @description Search query (ICAO code prefix) */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching airports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFlightRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight routes with airport coordinates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightRoutesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAirportStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportStats"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
