/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Create a new user account with email and password
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email and password to receive JWT tokens
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Use refresh token to obtain a new access token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the authenticated user's profile information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Update the authenticated user's profile information
         */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/licenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's licenses
         * @description Get all licenses for the authenticated user
         */
        get: operations["listLicenses"];
        put?: never;
        /**
         * Create a new license
         * @description Add a new pilot license for the authenticated user
         */
        post: operations["createLicense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licenses/{licenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get license details
         * @description Retrieve details of a specific license
         */
        get: operations["getLicense"];
        put?: never;
        post?: never;
        /**
         * Delete license
         * @description Delete a license and all associated flight logs
         */
        delete: operations["deleteLicense"];
        options?: never;
        head?: never;
        /**
         * Update license
         * @description Update license information
         */
        patch: operations["updateLicense"];
        trace?: never;
    };
    "/licenses/{licenseId}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get license statistics
         * @description Get hour totals and flight counts for a license
         */
        get: operations["getLicenseStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licenses/{licenseId}/currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check currency status
         * @description Check if pilot is current according to EASA/FAA regulations
         */
        get: operations["getLicenseCurrency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flights
         * @description Get flights for the authenticated user, optionally filtered by license
         */
        get: operations["listFlights"];
        put?: never;
        /**
         * Create flight log
         * @description Create a new flight log entry
         */
        post: operations["createFlight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flights/{flightId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flight details
         * @description Retrieve details of a specific flight
         */
        get: operations["getFlight"];
        /**
         * Update flight
         * @description Update an existing flight log entry
         */
        put: operations["updateFlight"];
        post?: never;
        /**
         * Delete flight
         * @description Delete a flight log entry
         */
        delete: operations["deleteFlight"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: email
             * @example pilot@example.com
             */
            email: string;
            /** @example John Doe */
            name: string;
            /**
             * Format: date-time
             * @example 2026-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T14:45:00Z
             */
            updatedAt: string;
        };
        AuthResponse: {
            /**
             * @description JWT access token (15 minutes validity)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description JWT refresh token (7 days validity)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
            /**
             * @description Access token expiry in seconds
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        /**
         * @description License type:
         *     - EASA_PPL: EASA Private Pilot License
         *     - FAA_PPL: FAA Private Pilot Certificate
         *     - EASA_SPL: EASA Sailplane Pilot License
         *     - FAA_SPORT: FAA Sport Pilot Certificate
         *     - EASA_CPL: EASA Commercial Pilot License
         *     - FAA_CPL: FAA Commercial Pilot Certificate
         *     - EASA_ATPL: EASA Airline Transport Pilot License
         *     - FAA_ATPL: FAA Airline Transport Pilot Certificate
         *     - EASA_IR: EASA Instrument Rating
         *     - FAA_IR: FAA Instrument Rating
         * @enum {string}
         */
        LicenseType: "EASA_PPL" | "FAA_PPL" | "EASA_SPL" | "FAA_SPORT" | "EASA_CPL" | "FAA_CPL" | "EASA_ATPL" | "FAA_ATPL" | "EASA_IR" | "FAA_IR";
        License: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            userId: string;
            licenseType: components["schemas"]["LicenseType"];
            /** @example PPL-123456 */
            licenseNumber: string;
            /**
             * Format: date
             * @example 2020-01-15
             */
            issueDate: string;
            /**
             * Format: date
             * @description Null if license doesn't expire
             * @example 2025-01-15
             */
            expiryDate?: string | null;
            /**
             * @description e.g., EASA, FAA, CAA UK
             * @example EASA
             */
            issuingAuthority: string;
            /**
             * @description Whether license is currently active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @example 2020-01-15T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-20T12:00:00Z
             */
            updatedAt: string;
        };
        LicenseCreate: {
            licenseType: components["schemas"]["LicenseType"];
            /** @example PPL-123456 */
            licenseNumber: string;
            /**
             * Format: date
             * @example 2020-01-15
             */
            issueDate: string;
            /**
             * Format: date
             * @example 2025-01-15
             */
            expiryDate?: string | null;
            /** @example EASA */
            issuingAuthority: string;
        };
        Flight: {
            /**
             * Format: uuid
             * @example 770e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId: string;
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * Format: date
             * @example 2026-01-30
             */
            date: string;
            /**
             * @description Aircraft registration
             * @example D-EFGH
             */
            aircraftReg: string;
            /**
             * @description Aircraft type
             * @example C172
             */
            aircraftType: string;
            /**
             * @description ICAO code of departure airport
             * @example EDDF
             */
            departureIcao?: string | null;
            /**
             * @description ICAO code of arrival airport
             * @example EDDH
             */
            arrivalIcao?: string | null;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC. Marks the beginning of block time per EASA FCL.010 / FAA 14 CFR 1.1.
             * @example 14:15:00
             */
            offBlockTime?: string | null;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC. Marks the end of block time per EASA FCL.010 / FAA 14 CFR 1.1.
             * @example 16:55:00
             */
            onBlockTime?: string | null;
            /**
             * Format: time
             * @description Takeoff time in UTC. Marks the beginning of airborne/flight time.
             * @example 14:30:00
             */
            departureTime?: string | null;
            /**
             * Format: time
             * @description Landing time in UTC. Marks the end of airborne/flight time.
             * @example 16:45:00
             */
            arrivalTime?: string | null;
            /**
             * Format: float
             * @description Total flight time in hours
             * @example 2.5
             */
            totalTime: number;
            /**
             * Format: float
             * @description Pilot-in-command time in hours
             * @example 2.5
             */
            picTime: number;
            /**
             * Format: float
             * @description Dual instruction time in hours
             * @example 0
             */
            dualTime: number;
            /**
             * Format: float
             * @description Solo flight time in hours
             * @example 0
             */
            soloTime: number;
            /**
             * Format: float
             * @description Night flying time in hours
             * @example 0.5
             */
            nightTime: number;
            /**
             * Format: float
             * @description Instrument flight time in hours
             * @example 1
             */
            ifrTime: number;
            /**
             * @description Number of day landings
             * @example 3
             */
            landingsDay: number;
            /**
             * @description Number of night landings
             * @example 1
             */
            landingsNight: number;
            /**
             * @description Free text notes
             * @example Training flight - touch and go practice
             */
            remarks?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-30T16:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-30T16:00:00Z
             */
            updatedAt: string;
        };
        FlightCreate: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * Format: date
             * @example 2026-01-30
             */
            date: string;
            /** @example D-EFGH */
            aircraftReg: string;
            /** @example C172 */
            aircraftType: string;
            /** @example EDDF */
            departureIcao?: string | null;
            /** @example EDDH */
            arrivalIcao?: string | null;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC
             * @example 14:15:00
             */
            offBlockTime?: string | null;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC
             * @example 16:55:00
             */
            onBlockTime?: string | null;
            /**
             * Format: time
             * @description Takeoff time in UTC
             * @example 14:30:00
             */
            departureTime?: string | null;
            /**
             * Format: time
             * @description Landing time in UTC
             * @example 16:45:00
             */
            arrivalTime?: string | null;
            /**
             * Format: float
             * @example 2.5
             */
            totalTime: number;
            /**
             * Format: float
             * @default 0
             * @example 2.5
             */
            picTime: number;
            /**
             * Format: float
             * @default 0
             * @example 0
             */
            dualTime: number;
            /**
             * Format: float
             * @default 0
             * @example 0
             */
            soloTime: number;
            /**
             * Format: float
             * @default 0
             * @example 0.5
             */
            nightTime: number;
            /**
             * Format: float
             * @default 0
             * @example 1
             */
            ifrTime: number;
            /**
             * @default 0
             * @example 3
             */
            landingsDay: number;
            /**
             * @default 0
             * @example 1
             */
            landingsNight: number;
            /** @example Training flight - touch and go practice */
            remarks?: string | null;
        };
        FlightUpdate: {
            /** Format: date */
            date?: string;
            aircraftReg?: string;
            aircraftType?: string;
            departureIcao?: string | null;
            arrivalIcao?: string | null;
            /**
             * Format: time
             * @description Off-block time (chocks off / engine start) in UTC
             */
            offBlockTime?: string | null;
            /**
             * Format: time
             * @description On-block time (chocks on / engine shutdown) in UTC
             */
            onBlockTime?: string | null;
            /**
             * Format: time
             * @description Takeoff time in UTC
             */
            departureTime?: string | null;
            /**
             * Format: time
             * @description Landing time in UTC
             */
            arrivalTime?: string | null;
            /** Format: float */
            totalTime?: number;
            /** Format: float */
            picTime?: number;
            /** Format: float */
            dualTime?: number;
            /** Format: float */
            soloTime?: number;
            /** Format: float */
            nightTime?: number;
            /** Format: float */
            ifrTime?: number;
            landingsDay?: number;
            landingsNight?: number;
            remarks?: string | null;
        };
        Statistics: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * @description Total number of flights
             * @example 150
             */
            totalFlights: number;
            /**
             * Format: float
             * @description Total flight hours
             * @example 385.5
             */
            totalHours: number;
            /**
             * Format: float
             * @description Total PIC hours
             * @example 320
             */
            picHours: number;
            /**
             * Format: float
             * @description Total dual instruction hours
             * @example 45.5
             */
            dualHours: number;
            /**
             * Format: float
             * @description Total solo hours
             * @example 20
             */
            soloHours: number;
            /**
             * Format: float
             * @description Total night hours
             * @example 15.5
             */
            nightHours: number;
            /**
             * Format: float
             * @description Total IFR hours
             * @example 30
             */
            ifrHours: number;
            /**
             * @description Total day landings
             * @example 450
             */
            landingsDay: number;
            /**
             * @description Total night landings
             * @example 35
             */
            landingsNight: number;
        };
        Currency: {
            /**
             * Format: uuid
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            licenseId: string;
            /**
             * @description Overall currency status
             * @example true
             */
            isCurrent: boolean;
            /**
             * @description Day currency status
             * @example true
             */
            daysCurrent: boolean;
            /**
             * @description Night currency status (FAA requires separate tracking)
             * @example false
             */
            nightsCurrent: boolean;
            last90Days: {
                /**
                 * @description Number of flights in last 90 days
                 * @example 8
                 */
                flights: number;
                /**
                 * @description Total landings in last 90 days
                 * @example 15
                 */
                totalLandings: number;
                /**
                 * @description Day landings in last 90 days
                 * @example 12
                 */
                dayLandings: number;
                /**
                 * @description Night landings in last 90 days
                 * @example 3
                 */
                nightLandings: number;
            };
            requiredLandings?: {
                /**
                 * @description Required day landings for currency
                 * @example 3
                 */
                day: number;
                /**
                 * @description Required night landings for night currency
                 * @example 3
                 */
                night: number;
            };
            /**
             * Format: date
             * @description License expiry date if applicable
             * @example 2025-01-15
             */
            expiryDate?: string | null;
        };
        PaginatedFlights: {
            data: components["schemas"]["Flight"][];
            pagination: {
                /**
                 * @description Current page (1-indexed)
                 * @example 1
                 */
                page: number;
                /**
                 * @description Items per page
                 * @example 20
                 */
                pageSize: number;
                /**
                 * @description Total number of items
                 * @example 150
                 */
                total: number;
                /**
                 * @description Total number of pages
                 * @example 8
                 */
                totalPages: number;
            };
        };
        Error: {
            /**
             * @description Error message
             * @example Validation failed
             */
            error: string;
            /** @description Detailed validation errors */
            details?: {
                /** @example totalTime */
                field?: string;
                /** @example Must be greater than 0 */
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Bad request - validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Validation failed",
                 *       "details": [
                 *         {
                 *           "field": "totalTime",
                 *           "message": "Must be greater than 0"
                 *         },
                 *         {
                 *           "field": "nightTime",
                 *           "message": "Cannot exceed total time"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description License UUID */
        LicenseId: string;
        /** @description Flight UUID */
        FlightId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example pilot@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @description Must be at least 8 characters
                     * @example SecurePass123!
                     */
                    password: string;
                    /** @example John Doe */
                    name: string;
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example pilot@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example SecurePass123!
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New access token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** @description Token expiry in seconds */
                        expiresIn?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listLicenses: {
        parameters: {
            query?: {
                /** @description Filter by active status */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of licenses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLicense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LicenseCreate"];
            };
        };
        responses: {
            /** @description License created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLicense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    expiryDate?: string | null;
                    isActive?: boolean;
                };
            };
        };
        responses: {
            /** @description License updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["License"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLicenseStatistics: {
        parameters: {
            query?: {
                /** @description Filter from this date (inclusive) */
                startDate?: string;
                /** @description Filter to this date (inclusive) */
                endDate?: string;
            };
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description License statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statistics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getLicenseCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description License UUID */
                licenseId: components["parameters"]["LicenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currency status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listFlights: {
        parameters: {
            query?: {
                /** @description Filter by license ID */
                licenseId?: string;
                /** @description Filter from this date (inclusive) */
                startDate?: string;
                /** @description Filter to this date (inclusive) */
                endDate?: string;
                /** @description Filter by aircraft registration */
                aircraftReg?: string;
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
                /** @description Sort field */
                sortBy?: "date" | "totalTime" | "createdAt";
                /** @description Sort order */
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of flights */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFlights"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFlight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightCreate"];
            };
        };
        responses: {
            /** @description Flight created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightUpdate"];
            };
        };
        responses: {
            /** @description Flight updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight UUID */
                flightId: components["parameters"]["FlightId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
