/** DEV-ONLY fixtures for the flight preview entries. Not part of the app build. */
import type { components } from './api/schema';

type Flight = components['schemas']['Flight'];

const base: Flight = {
  id: '1',
  userId: 'u1',
  date: '2026-01-15',
  aircraftReg: 'D-EFGH',
  aircraftType: 'C172',
  departureIcao: 'EDDF',
  arrivalIcao: 'EDDH',
  departureAirportName: 'Frankfurt am Main Airport',
  arrivalAirportName: 'Hamburg Airport',
  offBlockTime: '10:00:00',
  onBlockTime: '11:30:00',
  departureTime: '10:12:00',
  arrivalTime: '11:22:00',
  totalTime: 90,
  isSimulator: false,
  isPassenger: false,
  isPic: true,
  isDual: false,
  picTime: 90,
  dualTime: 0,
  nightTime: 0,
  ifrTime: 0,
  landingsDay: 1,
  landingsNight: 0,
  allLandings: 1,
  takeoffsDay: 1,
  takeoffsNight: 0,
  soloTime: 0,
  crossCountryTime: 90,
  distance: 220.4,
  sicTime: 0,
  dualGivenTime: 0,
  simulatedFlightTime: 0,
  groundTrainingTime: 0,
  createdAt: '2026-01-15T12:00:00Z',
  updatedAt: '2026-01-15T12:00:00Z',
};

export const previewFlights: Flight[] = [
  {
    ...base,
    id: '1',
    remarks: 'IFR cross-country, ILS 23 into Hamburg. Light rime in the climb.',
    ifrTime: 65,
    nightTime: 25,
    approachesCount: 2,
    holds: 1,
    actualInstrumentTime: 40,
    simulatedInstrumentTime: 0,
    approaches: [
      { type: 'ILS', airport: 'EDDH', runway: '23' },
      { type: 'RNAV/GPS', airport: 'EDDF', runway: '07C' },
    ],
    signatureId: 'sig-1',
    picName: 'Frederic Jaeckel',
    route: 'EDDF,WRB,EDDH',
  },
  {
    ...base,
    id: '2',
    date: '2026-01-11',
    departureIcao: 'EDQE',
    arrivalIcao: 'EDQE',
    departureAirportName: 'Burg Feuerstein Airport',
    arrivalAirportName: 'Burg Feuerstein Airport',
    offBlockTime: '08:05:00',
    onBlockTime: '08:50:00',
    departureTime: '08:10:00',
    arrivalTime: '08:47:00',
    totalTime: 45,
    picTime: 0,
    dualTime: 45,
    isSimulator: false,
    isPassenger: false,
    isPic: false,
    isDual: true,
    crossCountryTime: 0,
    distance: 0,
    landingsDay: 6,
    allLandings: 6,
    takeoffsDay: 6,
    instructorName: 'M. Berger',
    remarks: 'Circuits, crosswind landings.',
  },
  {
    ...base,
    id: '3',
    date: '2026-01-04',
    departureIcao: 'Meadow strip near Kassel',
    departureAirportName: null,
    arrivalIcao: 'EDVK',
    arrivalAirportName: 'Kassel Calden Airport',
    offBlockTime: '13:20:00',
    onBlockTime: '13:55:00',
    departureTime: '13:24:00',
    arrivalTime: '13:52:00',
    totalTime: 35,
    picTime: 35,
    soloTime: 35,
    crossCountryTime: 0,
    distance: 12.2,
    launchMethod: 'winch',
    remarks: null,
  },
  {
    // Both ends off-airport, one of them long — the worst case for the route line
    ...base,
    id: '6',
    date: '2026-01-02',
    departureIcao: 'Meadow strip near Kassel',
    departureAirportName: null,
    arrivalIcao: 'North field, Bad Hersfeld-Johannesberg',
    arrivalAirportName: null,
    offBlockTime: '11:05:00',
    onBlockTime: '11:40:00',
    departureTime: '11:08:00',
    arrivalTime: '11:37:00',
    totalTime: 35,
    picTime: 35,
    crossCountryTime: 35,
    distance: 18.6,
    launchMethod: 'aerotow',
    remarks: 'Out-and-return, no ICAO at either end.',
  },
  {
    // A short site name — must not be abbreviated at all
    ...base,
    id: '8',
    date: '2026-01-03',
    departureIcao: 'Home strip',
    departureAirportName: null,
    arrivalIcao: 'EDQE',
    arrivalAirportName: 'Burg Feuerstein Airport',
    offBlockTime: '15:10:00',
    onBlockTime: '15:38:00',
    departureTime: '15:13:00',
    arrivalTime: '15:35:00',
    totalTime: 28,
    picTime: 28,
    crossCountryTime: 0,
    distance: 9.4,
    remarks: null,
  },
  {
    // A single long word — nothing to cut on but the word itself
    ...base,
    id: '9',
    date: '2025-12-27',
    departureIcao: 'Segelfluggelaende Klippeneck',
    departureAirportName: null,
    arrivalIcao: 'Grass strip Hohenfels',
    arrivalAirportName: null,
    offBlockTime: '12:00:00',
    onBlockTime: '12:52:00',
    departureTime: '12:03:00',
    arrivalTime: '12:49:00',
    totalTime: 52,
    picTime: 52,
    crossCountryTime: 52,
    distance: 41.3,
    launchMethod: 'winch',
    remarks: null,
  },
  {
    // A code the airport database does not carry — no name comes back
    ...base,
    id: '7',
    date: '2025-12-30',
    departureIcao: 'EDXY',
    departureAirportName: null,
    arrivalIcao: 'EDXY',
    arrivalAirportName: null,
    offBlockTime: '14:00:00',
    onBlockTime: '14:25:00',
    departureTime: '14:03:00',
    arrivalTime: '14:22:00',
    totalTime: 25,
    picTime: 25,
    crossCountryTime: 0,
    distance: 0,
    landingsDay: 3,
    allLandings: 3,
    takeoffsDay: 3,
    remarks: null,
  },
  {
    ...base,
    id: '4',
    date: '2025-12-22',
    departureIcao: 'LSZH',
    arrivalIcao: 'LFMD',
    departureAirportName: 'Zurich Airport',
    arrivalAirportName: 'Cannes-Mandelieu Airport',
    offBlockTime: '17:40:00',
    onBlockTime: '20:15:00',
    departureTime: '17:52:00',
    arrivalTime: '20:08:00',
    totalTime: 155,
    picTime: 155,
    nightTime: 60,
    ifrTime: 155,
    crossCountryTime: 155,
    distance: 310.8,
    landingsNight: 1,
    landingsDay: 0,
    allLandings: 1,
    takeoffsDay: 1,
    takeoffsNight: 0,
    multiPilotTime: 155,
    sicTime: 0,
    crewMembers: [
      { id: 'c1', flightId: '4', role: 'SIC', name: 'A. Weber' },
      { id: 'c2', flightId: '4', role: 'Passenger', name: 'L. Roth' },
    ],
    remarks: 'Night arrival over the Alps. Smooth all the way.',
  },
  {
    ...base,
    id: '5',
    date: '2025-12-08',
    departureIcao: 'EDDS',
    arrivalIcao: 'EDDS',
    departureAirportName: 'Stuttgart Airport',
    arrivalAirportName: 'Stuttgart Airport',
    offBlockTime: '09:00:00',
    onBlockTime: '11:00:00',
    departureTime: '09:05:00',
    arrivalTime: '10:55:00',
    totalTime: 120,
    picTime: 0,
    dualTime: 120,
    isSimulator: false,
    isPassenger: false,
    isPic: false,
    isDual: true,
    simulatedFlightTime: 120,
    groundTrainingTime: 60,
    fstdType: 'FNPT II MCC',
    isProficiencyCheck: true,
    crossCountryTime: 0,
    distance: 0,
    landingsDay: 4,
    allLandings: 4,
    takeoffsDay: 4,
    endorsements: 'FCL.740.A proficiency check — SEP(land) revalidation.',
    instructorName: 'K. Neumann',
    instructorComments: 'Good situational awareness throughout. Watch the descent profile on the RNAV.',
  },
];
